# Generated by Django 3.2.9 on 2022-11-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_genre',
            field=models.CharField(default='액션', max_length=10),
            preserve_default=False,
        ),
    ]
